
[workspace]
members = [ "bin/luoxide-cli",
  "crates/luoxide",
  "crates/luoxide-bench",
  "crates/luoxide-macros",
  "crates/luoxide-parser",
  "crates/luoxide-text",
  "xtask"
]
resolver = "3"

[workspace.package]
edition = "2024"
authors = [""]
license = "MIT"

[workspace.dependencies]
luoxide-parser = { path = "crates/luoxide-parser" }
luoxide-text = { path = "crates/luoxide-text" }

thiserror = "2.0.6"
insta = "1.41.1"
tracing = "0.1.44"
thin-vec = "0.2.18"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }

[profile.dev]
opt-level = 0