[package]
name = "Luoxidant"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "bin/luoxide-cli",
  "crates/luoxide",
  "crates/luoxide-ast",
  "crates/luoxide-bench",
  "crates/luoxide-macros",
  "crates/luoxide-parser",
  "crates/luoxide-text",
  "xtask"
]

[workspace.package]
edition = "2021"
authors = [""]
license = "MIT"

[workspace.dependencies]
luoxide-parser = { path = "crates/luoxide-parser" }
luoxide-ast = { path = "crates/luoxide-ast" }
luoxide-text = { path = "crates/luoxide-text" }

thiserror = "1.0"
insta = "1.39"
tracing = "0.1.9"

[lib]
name = "luoxidant"
path = "src/lib.rs"

[[bin]]
name = "luoxidant"
path = "src/bin/main.rs"

[features]
default = [
  "__assert_snapshots",
]

# private features
__assert_snapshots = []


[dependencies]
thiserror = { workspace = true }

env_logger = "0.11"
hexfloat2 = "0.1.3"
log = { version = "0.4", features = ["serde"] }
logos = "0.14"
rand = "0.8"

[dev-dependencies]
insta = { workspace = true }
