[package]
name = "luoxide-parser"
version = "0.0.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]

[[bin]]
name = "luoxide-parser"
path = "src/bin/main.rs"

[features]
default = [
  "__assert_snapshots",
]

# private features
__assert_snapshots = []

[dependencies]
luoxide-ast = { workspace = true }
luoxide-text = { workspace = true }

tracing = { workspace = true }
thiserror = { workspace = true }
thin-vec = { workspace = true }

#logos = { version = "^0.16", features = ["debug"] }
logos = { version = "^0.16" }
hexfloat2 = "0.2.0"
ecow = "0.2.2"
camino = "1.1.9"
termcolor = "1.4.1"
codespan-reporting = "0.11.1"
bumpalo = { version = "3.16", features = ["collections"] }

[dev-dependencies]
insta = { workspace = true, features = ["glob"]  }
tracing-subscriber = "0.3.18"
codespan-reporting = "0.11.1"


[profile.dev]
opt-level = 0
