[package]
name = "luoxide-text"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ahash = "0.8.12"
codespan = "0.13.1"
rustc-hash = "2.1.3"
serde = { version = "1.0.211", optional = true, features = ["derive"] }
string-interner = { version = "0.20.0", default-features = false, features = ["std", "backends"] }

[features]
default = [
  "serde",
]
serde = [
  "dep:serde",
]
