/// Lua grammar
/// This grammar is based on the Lua 5.3 Reference Manual

/// Program
lua = _{ SOI ~ chunk ~ EOI }

/// Chunk
chunk = _{ block }

/// List of statements
block = { (statement )* ~ return_statement? }

/// Statements
statement = {
    ";" |
    assign_statement |
    local_assign_statement |
    exp |
    do_statement |
    functioncall |
    label |
    break |
    goto ~ Name |
    do_statement |
    control_structure |
    function ~ funcname ~ funcbody |
    local ~ function ~ Name ~ funcbody
}
    assign_statement = { varlist ~ assign_op ~ explist }
    local_assign_statement = { local ~ assign_statement }
    do_statement = { do ~ block ~ end }
    return_statement = { return ~ (explist)? }
    funcname = { Name ~ ("." ~ Name)? ~ (":" ~ Name)? }


// Control structures
control_structure = { if_statement | while_statement | repeat_statement | for_statement }
    while_statement = { while ~ exp ~ do ~ block ~ end }
    for_statement = { for ~ Name ~ "=" ~ exp ~ "," ~ exp ~ ("," ~ exp)? ~ do ~ block ~ end }
    repeat_statement = { repeat ~ block ~ until ~ exp }
    if_statement = { if ~ exp ~ then ~ block ~ (elseif_statement)* ~ (else_statement)? ~ end }
        elseif_statement = { elseif ~ exp ~ then ~ block }
        else_statement = { else ~ block }

// Expressions
exp = _{ binop_expression | unary_expression | primary_expression }

binop_expression = {
    primary_expression ~ binop ~ exp
}

unary_expression = {
    unaryop ~ exp
}

primary_expression = {
    prefixexp |
    literal |
    functiondef |
    "(" ~ exp ~ ")"
}
Numeral = { hex | number | float }

explist = { exp ~ ("," ~ exp)* }
prefixexp = { var ~ prefixexp_tail* | "(" ~ exp ~ ")" ~ prefixexp_tail* }

prefixexp_tail = {"[" ~ exp ~ "]" | "." ~ Name | ":" ~ Name ~ args | args}

// Functions and function calls
functiondef = { function ~ funcbody }
functioncall = { prefixexp ~ args | prefixexp ~ ":" ~ Name ~ args }

args = { "(" ~ (explist)? ~ ")" | string } // TODO: tableconstructor
funcbody = { "(" ~ ("..." | (parlist)?) ~ ")" ~ block ~ end }
parlist = { namelist ~ ("," ~ "...")? }

// Variables
var = @{ Name ~ var_tail? }
var_tail = @{ "[" ~ exp ~ "]" ~ var_tail? | "." ~ Name ~ var_tail? }
varlist = _{ var ~ ("," ~ var)* }

// Labels
label = _{ "::" ~ Name ~ "::" }

// Operators
operator = ${ binop | unaryop | assign_op }
    // Binary
    binop = ${ relational | arithmetic | bitwise | logic | other }
        // Arithmetic
        arithmetic = ${ add_op | sub_op | mul_op | div_op | floor_div_op | mod_op | exp_op }
            add_op = @{ "+" }
            sub_op = @{ "-" }
            mul_op = @{ "*" }
            div_op = @{ "/" }
            floor_div_op = @{ "//" }
            mod_op = @{ "%" }
            exp_op = @{ "^" }
        // Logic
        logic = ${ and_op | or_op }
            and_op = @{ "and" }
            or_op = @{ "or" }
        // Bitwise
        bitwise = ${ band_op | bor_op | bxor_op | bnot_op | shl_op | shr_op }
            band_op = @{ "&" }
            bor_op = @{ "|" }
            bxor_op = @{ "~" }
            bnot_op = @{ "!" }
            shl_op = @{ "<<" }
            shr_op = @{ ">>" }
        // Relational
        relational = ${ eq_op | neq_op | lt_op | gt_op | leq_op | geq_op }
            eq_op = @{ "==" }
            neq_op = @{ "~=" }
            lt_op = @{ "<" }
            gt_op = @{ ">" }
            leq_op = @{ "<=" }
            geq_op = @{ ">=" }
        // Other
        other = ${ concat_op }
            concat_op = @{ ".." }
    // Unary
    unaryop = ${ len_op | not_op | unary_op | bitwise_unary_op }
        len_op = @{ "#" }
        not_op = @{ "not" }
        unary_op = @{ "-" }
        bitwise_unary_op = @{ "~" }
    // Assign
    assign_op = @{ "=" }

// Literals
literal = ${ number | string | boolean | nil | Name }
    boolean = @{ true | false }

    // Names (not keywords)
    Name = @{ !keyword ~ identifier }
        identifier = _{ letter ~ (letter | digit | "_")* }

    namelist = _{ Name ~ ("," ~ Name)* }

    // Numbers (assume integers for simplicity)
    number = @{ digit+ | hex }

    // Hexadecimal numbers
    hex = @{ "0x" ~ HEX_DIGIT+ }

    // Floating point numbers
    float = @{ DECIMAL_NUMBER ~ ("." ~ DECIMAL_NUMBER)? ~ (("e" | "E") ~ ("+" | "-")? ~ DECIMAL_NUMBER)? } // TODO: check if this is correct

    // Letters (lowercase or uppercase)
    letter = _{ ASCII_ALPHA }

    // Digits
    digit = _{ ASCII_DIGIT }

    // String
    string = {
    	long_string |
        "\"" ~ (string_content) ~ "\"" |
        "'" ~ (string_content) ~ "'"
    }
    
    long_string = _{
        "[[" ~ (!("]]") ~ ANY)* ~ "]]"
    }
    
    string_content = { (string_char | escape_sequence)* }
    string_char = _{ (!("\"" | "'" | "\\") ~ ANY) } 
    escape_sequence = _{
        "\\" ~ (
            "\""  // Double quote
          | "'"  // Single quote
          | "\\"  // Backslash
          | "a"  // Bell
          | "b"  // Backspace
          | "f"  // Form feed
          | "n"  // Newline
          | "r"  // Carriage return
          | "t"  // Horizontal tab
          | "v"  // Vertical tab
          | "x" ~ HEX_DIGIT ~ HEX_DIGIT  // Hexadecimal character
          | UNICODE_ESCAPE_SEQUENCE  // Unicode character
        )
    }
    UNICODE_ESCAPE_SEQUENCE = _{ "u{" ~ HEX_DIGIT{1,6} ~ "}" }

// Keywords
keyword 
  = @{ and | break | do | else | elseif | end |
    false | for | function | goto | if | in |
    local | nil | not | or | repeat | return |
    then | true | until | while }

    and = _{ "and" }
    break = _{ "break" }
    do = _{ "do" }
    else = _{ "else" }
    elseif = _{ "elseif" }
    end = _{ "end" }
    false = _{ "false" }
    for = _{ "for" }
    function = _{ "function" }
    goto = _{ "goto" }
    if = _{ "if" }
    in = _{ "in" }
    local = _{ "local" }
    nil = _{ "nil" }
    not = _{ "not" }
    or = _{ "or" }
    repeat = _{ "repeat" }
    return = _{ "return" }
    then = _{ "then" }
    true = _{ "true" }
    until = _{ "until" }
    while = _{ "while" }

// Optional whitespace (including all standard ASCII whitespace characters)
WHITESPACE = _{ " " | "\t" | EOL }
SPACE = _{ SPACE_SEPARATOR }

// Comment
line_comment = _{ "--" ~ ((!EOL ~ ANY)*)? ~ EOL }
block_comment = _{ "--[[" ~ (!("]]") ~ ANY)* ~ "]]" }
COMMENT = _{ block_comment | line_comment }

// End of line
EOL = _{ NEWLINE }